### ISSUE TITLE
impossible de démmarer E

### ISSUE THREAD

**Issue by gamersalpha** [batden/elegantbeaver#2]
Bonjour, 

aprés une compilation qui semble correcte, j'arrive à démmarer E mais je boucle sur l'initialisation de e.

impossible d'arriver sur le bureau, il me demande en boucle et en boucle les premiers paramétre de E.

je ne trouve pas de fichier de log, tu saurais comment débuger ce probléme de démmarage de E stp ?

j'ai regarde dans mon profil mais aucun .xsession-errors

**Comment by gamersalpha** [comment]
probléme corrigé seul aprés mise à jour des dépots

**Comment by batden** [comment]
Salut Issa,

Merci pour tes retours. Mais je n'ai pas le temps de répondre que tu as déjà clos les rapports ;)

En ce qui concerne la boucle sans fin du _wizard_ de E, raster a effectivement réglé le problème après un échange de courriels entre Carla Sensa et lui, sur la liste des utilisateurs. Carla est le pseudo de ma compagne, elle m'aide à maintenir les scripts, et je valide tout ce qu'elle peut dire puisqu'elle est aussi une utilisatrice de longue date d'Enlightenment.

Je te conseille d'aller régulièrement voir sur la liste ci-dessous ou de t'inscrire si ce n'est pas déjà fait :
https://sourceforge.net/p/enlightenment/mailman/enlightenment-users/

Ha oui ! Sympa ton avatar de Boo forme parfaite sur Github :)

**Comment by gamersalpha** [comment]
Hello, 
merci pour ton retour, tu as un lien de ta siciété Carla je suis curieux de savoir ce que tu fait en te basant sur les EFL ?


les ML j'aime pas du tout, je comprend pas que ça existe encore :/ , je pérférerais allé sur discord à la rigeur sur IRC ou un forum, ùais les emails, j'ai peux plus de ces trucs; je supporte plus, ça devrait etre utiliser que pour de la notif mais pour échanger concrétement, bon c'est un autre débat
 
je suis sur les IRC e.fr, mais aussi e, mais tu n'est pas la bas, c'est dommage ?


merci pour mon avatar, j'adore aussi :)

@ la prochaine
