### ISSUE TITLE
Ajouter des apps à l'installeur

### ISSUE THREAD

**Issue by gamersalpha** [batden/elegantbeaver#3]
Bonjour est il possible d'ajouter des applications à l'installeur : 

Eflete - GUI Theme design tool
Enventor GUI Edje file design tool

peut d'autre si tu connais d'autre apps en efl à tester ?

merci par avance :)

**Comment by batden** [comment]
Par le passé, je fournissais des scripts très longs, permettant d'installer de nombreuses applications de l'environnement, plus des bindings (python...), des thèmes, des traductions supplémentaires, etc. J'ai arrêté pour me concentrer sur l'essentiel et fournir une base solide à l'utilisateur curieux de découvrir Enlightenment, tout en respectant le plus possible le système préexistant. En fait, c'était devenu ingérable et j'y passais vraiment tout mon temps, pour un résultat peu satisfaisant.

Les applications dont tu parles ciblent les designers et le programmeurs; c'est un niveau bien supérieur à celui de l'utilisateur lambda à qui s'adresse mes scripts. En outre, ces applications (comme beaucoup d'autres que l'on peut trouver dans les dépôts de l'environnement) souffrent d'un développement  très irrégulier car elles sont peu utilisées... et donc contiennent plus de bogues.

J'ai hésité à ajouter Rage (lecteur vidéo) à mes scripts, car c'est un programme créé et maintenu par raster lui-même, mais il existent déjà tant d'alternatives disponibles dans Ubuntu que je n'en vois pas l'utilité. Et Rage va s'ajouter aux lecteurs disponibles dans l'applet gérant le son... voire même s'ouvrir par défaut quand l'utilisateur clique sur une vidéo !
