### ISSUE TITLE
make directories configurable

### ISSUE THREAD

**Issue by mhinsch** [batden/elegantbeaver#4]
A lot of the directory infrastructure is (sort of) hard-coded at the moment. It would be nice if you could configure it. Like many people (at least those who grew up with the command line) I tend to be quite particular when it comes to the layout of my home directory, forcing me to use e.g. ~/elegantbeaver or ~/Documents/sources makes this script a non-starter for me.

**Comment by batden** [comment]
That's a good point. I'm currently working on a new script (aimed at Eoan Ermine users, for the time being) that allows users to select the path to the source folders.

**Comment by batden** [comment]
I hope that this new script will meet your expectations:
https://github.com/batden/eligible
Happy testing!
